server:
  port: 8083
spring:
  data:
    mongodb:
      host: mongodb://localhost:27017
      database: auth-rental
  application:
    name: auth-service

  zipkin:
    base-url: http://localhost:9411/


management:
  endpoints:
    web:
      exposure:
        include: '*'

jwt:
  secret:
    key: 21kkkktoopafeafgrrwwfwfwfe
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/