server:
  port: 8080

spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: auth-rental

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-service:8761/eureka

jwt:
  secret:
    key: 21kkkktoopafeafgrrwwfwfwfe
