version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: /
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
      - zipkin
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    image: /
    ports:
      - "8761:8761"
    depends_on:
      - zipkin
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: /
    ports:
      - "8080:8080"
    depends_on:
      - auth-mongo
      - discovery-service
      - api-gateway
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/auth-rental

  property-service:
    build:
      context: ./property-service
      dockerfile: Dockerfile
    image: /
    ports:
      - "8080:8080"
    depends_on:
      - property-mongo
      - kafka
      - zipkin
      - discovery-service
      - api-gateway
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/property-service

  tenant-service:
    build:
      context: ./tenant-service
      dockerfile: Dockerfile
    image: /
    ports:
      - "8080:8080"
    depends_on:
      - tenant-mongo
      - kafka
      - zipkin
      - discovery-service
      - api-gateway
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/tenant-service

  auth-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - auth-mongodb-data:/data/db

  property-mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - property-mongodb-data:/data/db

  tenant-mongo:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - tenant-mongodb-data:/data/db
volumes:
  auth-mongodb-data:
  property-mongodb-data:
  tenant-mongodb-data: