eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          predicates:
            - Path=/user/**
            - Path=/token/**
            - Path=/role/**
          uri: lb://auth-service
        - id: property-service
          predicates:
            - Path=/property/**
            - Path=/broker/**
          uri: lb://property-service
        - id: tenant-service
          predicates:
            - Path=/tenant/**
          uri: lb:/tenant-service
  zipkin:
    base-url: http://localhost:9411/


management:
  endpoints:
    web:
      exposure:
        include: '*'
