eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
server:
  port: 8761
spring:
  application:
    name: discovery-service
  zipkin:
    base-url: http://localhost:9411/

management:
  endpoints:
    web:
      exposure:
        include: '*'