spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: property-service
  application:
    name: property-service
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: tenant
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  zipkin:
    base-url: http://localhost:9411/

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

auto:
  create:
    topics:
      enable: true


topic:
  name:
    producer: tenant.create